[langserver]
dreamchecker = true

[code_standards]
disallow_relative_type_definitions = true
disallow_relative_proc_definitions = true

[dmdoc]
use_typepath_names = true

[debugger]
engine = "auxtools"

[map_renderer]
# Objects inside this list will never render
hide_invisible = [
"/obj/effect/landmark",
"/obj/effect/mapping_helpers",
"/obj/effect/spawner/random_barrier",
"/obj/effect/spawner/random_spawners",
]

[map_renderer.fancy_layers]
# This section allows for layer overrides on typepaths
# Layer -10
"/turf/simulated/floor/plating" = -10
"/turf/space" = -10
# Layer -2
"/turf/simulated/floor/bluegrid" = -2
"/turf/simulated/floor/carpet" = -2
"/turf/simulated/floor/engine" = -2
"/turf/simulated/floor/plasteel" = -2
"/turf/simulated/floor/wood" = -2
"/turf/simulated/wall" = -2

[map_renderer.render_passes]
# This section allows you to configure the various render passes
# You can force enable or disable them to make your map render better
smart-cables = false
